FROM lemp-php:7.3

# sendmail config
############################################
#
#RUN apt-get update && apt-get install -q -y ssmtp mailutils

## root is the person who gets all mail for userids < 1000
#RUN echo "root=filesharing@email.com" >> /etc/ssmtp/ssmtp.conf
#
## Here is the gmail configuration (or change it to your private smtp server)
#RUN echo "mailhub=smtp.gmail.com:587" >> /etc/ssmtp/ssmtp.conf
#RUN echo "AuthUser=nazar.10.17k@gmail.com" >> /etc/ssmtp/ssmtp.conf
#RUN echo "AuthPass=prometheusronaldinio1017" >> /etc/ssmtp/ssmtp.conf
#
#RUN echo "UseTLS=YES" >> /etc/ssmtp/ssmtp.conf
#RUN echo "UseSTARTTLS=YES" >> /etc/ssmtp/ssmtp.conf
#
#
## Set up php sendmail config
#RUN echo "sendmail_path=sendmail -i -t" >> /usr/local/etc/php/conf.d/php-sendmail.ini
